# Sistemas Lineares - Exercícios

In [0]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{:.4f}".format(x)}) # configura a impressão dos floats

def eliminacao(matriz):
  for i in range(matriz.shape[0]):
    pivo=matriz[i,i] #pivo elemento da diagonal principal
    equacao_pivo=matriz[i,:] #linha que representa a equacao pivo
    j=i+1 #para acessar as linhas a frente da pivo
    while(j<matriz.shape[0]): #enquanto nao chegar a ultima linha
      eliminador=matriz[j,i]/pivo #calculo o elemento que fara a eliminacao do termo
      matriz[j,:]=matriz[j,:]-(eliminador*equacao_pivo) #atualiza a linha que vai ter o elemento eliminado
      j=j+1 #acessa a proxima linha para fazer nova eliminacao
  return matriz 

def substituicao(matriz):
  solucoes=np.zeros(matriz.shape[0],dtype=float) #vetor de solucoes
  solucoes[-1]=matriz[-1,-1]/matriz[-1,-2] #a primeira solucao é conhecida
  soma=0
  for i in range(-(matriz.shape[0]-2),1): #vai da ultima linha ate a primeira. de n a 0
    for j in range(matriz.shape[0]): #para calcular as somas possiveis
      if(j!=-i): #epossivel somar quando eu conheco o valor de x descoberto na linha anterior. acesso o vetor de solucoes atraves do indice j
        soma+=solucoes[j]*matriz[-i,j] #faco as somas possiveis
    solucoes[-i]=(matriz[-i,-1]-soma)/matriz[-i,-i] #calculo a solucao
    soma=0 #zero o valor de soma para o proximo calculo na linha acima   
  print(solucoes)
  for k in range (matriz.shape[0]):
    print('x',k+1,' = ',solucoes[k],sep='') 
  return solucoes

def gauss_ingenuo(matriz_sistema):
  return substituicao(eliminacao(matriz_sistema))


def pivotamento(matriz):
  for i in range(matriz.shape[0]):
    maior_abs=np.abs(matriz[i,i])
    maior=matriz[i,i]
    for q in range(i+1,matriz.shape[0]): #for para procurar o maior numero nas linhas do pivo
      if(np.abs(matriz[q,i])>maior_abs): #se o numero encontrado for maior que o inicial
        maior=matriz[q,i] #entao o maior numero é o encontrado
        matriz[[i,q]]=matriz[[q,i]] #troco as linhas da matriz
    #print('i=',i,'\nmatriz=',matriz)
    pivo=maior #pivo elemento da diagonal principal
    equacao_pivo=matriz[i,:] #linha que representa a equacao pivo
    j=i+1 #para acessar as linhas a frente da pivo
    while(j<matriz.shape[0]): #enquanto nao chegar a ultima linha
      eliminador=matriz[j,i]/pivo #calculo o elemento que fara a eliminacao do termo
      matriz[j,:]=matriz[j,:]-(eliminador*equacao_pivo) #atualiza a linha que vai ter o elemento eliminado
      j=j+1 #acessa a proxima linha para fazer nova eliminacao
  return matriz 

def substituicao(matriz):
  solucoes=np.zeros(matriz.shape[0],dtype=float) #vetor de solucoes
  solucoes[-1]=matriz[-1,-1]/matriz[-1,-2] #a primeira solucao é conhecida
  soma=0
  for i in range(-(matriz.shape[0]-2),1): #vai da ultima linha ate a primeira. de n a 0
    for j in range(matriz.shape[0]): #para calcular as somas possiveis
      if(j!=-i): #e possivel somar quando eu conheco o valor de x descoberto na linha anterior. acesso o vetor de solucoes atraves do indice j
        soma+=solucoes[j]*matriz[-i,j] #faco as somas possiveis
    solucoes[-i]=(matriz[-i,-1]-soma)/matriz[-i,-i] #calculo a solucao
    soma=0 #zero o valor de soma para o proximo calculo na linha acima   
  print(solucoes)
  for k in range (matriz.shape[0]):
    print('x',k+1,' = ',solucoes[k],sep='') 
  return solucoes

def gauss_pivotamento(matriz_sistema):
  return substituicao(pivotamento(matriz_sistema))


def verificar_dominancia(matriz):
  for t in range(matriz.shape[0]):
    soma=0.0
    for j in range(matriz.shape[1]):
      if t!=j:
        soma+=matriz[t,j]
    if(np.abs(matriz[t,t])<np.abs(soma)):
      print('O sistema não possui convergencia garantida')
      return False
  print('O sistema converge')
  return True


def erro(novo,ant,taxa,vetor):
  a=np.zeros(novo.shape[0])
  for i in range(novo.shape[0]):
    a[i]=np.abs((novo[i]-ant[i])*100/novo[i])
    vetor.append(a[i])
  #print('erro=',a) #possibilita printar o vetor mostrando todos os erros encontrados, respectivamente na ordem para x1,x2,...,xn
  if max(a)<taxa: #se o erro for menor do que o requisitado na funcao, true para parar o laço
    return True
  return False

def gauss_seidel(matriz,iteracoes,t_erro,relaxamento,lambd):
  #relaxamento acelera convergencia se lambda>1 e o sistema convergir
  # tipicamente usado para fazer com que um sistema não-convergente passe a convergir se lambda<1
  #lambd entre 0 e 2
  atual=np.zeros(matriz.shape[0],dtype=float) #vetor com as soluçoes da iteração
  anteriores=atual.copy() #vetor para soluçoes anteriores para calculo do erro
  v_erro=[] #vetor para acumular os valores do erro
  soma=0.0 #variavel auxiliar temporaria
  for k in range(iteracoes): #ate o numero max de iterações
    for i in range(matriz.shape[0]): #em cada linha
      soma=0.0 #zera a variavel
      for j in range(matriz.shape[0]): #em cada coluna da linha
        if j!=i: #se nao esta na diagonal principal
          soma+=matriz[i,j]*atual[j] #soma an's*xn's
      atual[i]=(matriz[i,-1]-soma)/matriz[i,i] #calcula o valor de xn
      if relaxamento: #se usa a tecnica do relaxamento
        atual[i]=atual[i]*lambd+(1-lambd)*anteriores[i] #valor atual
    if (k>0): #apos a primeira iteração
      if(erro(atual,anteriores,t_erro,v_erro)): #calculo o erro
        break #se esta menor que o pedido breca o laço
      anteriores=atual.copy() #atualiza os valores do vetor anterior para as proximas iteraçoes
  print('numero de iteracoes: ',k+1) 
  #print('penultima iteração:')
  #for k in range (matriz.shape[0]):
    #print('x',k+1,' = ',anteriores[k],sep='')
  #print('resultado final:')  
  for k in range (matriz.shape[0]):
    print('x',k+1,' = ',atual[k],sep='') 
  return atual 

def dlu(matriz_sistema):
  matriz_sistema=matriz_sistema[matriz_sistema[:,0].argsort(kind='quicksort')][::-1] #ordena o sistema na ordem decrescente pela primeira coluna
  #print('matriz_sistema=\n',matriz_sistema)
  u=matriz_sistema[:,:-1] #matriz dos coeficientes
  b=matriz_sistema[:,-1] #matriz dos resultados
  l=np.identity(u.shape[0],dtype=float) #identidade, matriz l
  l,u,b=pivotamento_lu(u,l,b) #chama função para encontrar l e u
  return l,u,b

def pivotamento_lu(matriz_u,matriz_l,b):
  p=np.identity(matriz_u.shape[0])
  for i in range(matriz_u.shape[0]-1):
    maior_abs=np.abs(matriz_u[i,i]) #maior em modulo
    maior=matriz_u[i,i] #maior = primeiro numero da coluna
    for q in range(i+1,matriz_u.shape[0]): #for para procurar o maior numero nas linhas do pivo
      if(np.abs(matriz_u[q,i])>maior_abs): #se o numero encontrado for maior que o inicial
        maior=matriz_u[q,i] #entao o maior numero é o encontrado
        matriz_u[[i,q]]=matriz_u[[q,i]] #troco as linhas da matriz
        p[[i,q]]=p[[q,i]] #troco as linhas na matriz identidade
    pivo=maior 
    equacao_pivo=matriz_u[i,:] #linha que representa a equacao pivo
    j=i+1 #para acessar as linhas a frente da pivo
    while(j<matriz_u.shape[0]): #enquanto nao chegar a ultima linha
      eliminador=matriz_u[j,i]/pivo #calculo o elemento que fara a eliminacao do termo
      matriz_u[j,:]=matriz_u[j,:]-(eliminador*equacao_pivo) #atualiza a linha que vai ter o elemento eliminado
      matriz_l[j,i]=eliminador #preenche a matriz l
      j=j+1 #acessa a proxima linha para fazer nova eliminacao
  b=np.matmul(p,b) #multiplica b pela matriz identidade p
  return matriz_l,matriz_u,b

def matriz_d(l,b):
  d=np.zeros(l.shape[0],dtype=float) #numero de itens que compoem o vetor d
  soma=0.0
  for i in range(l.shape[0]): #para encontrar os valores de d, faz-se a substituiçao progressiva
    soma=0.0
    for j in range(l.shape[0]):
      if (j!=i):
        soma+=l[i,j]*d[j]
    d[i]=b[i]-soma
  return d

def solucao(u,d):
  solucoes=np.zeros(u.shape[0],dtype=float) #vetor de solucoes
  solucoes[-1]=d[-1]/u[-1,-1] #a primeira solucao é conhecida
  soma=0.0
  for i in range(-(u.shape[0]-2),1): #vai da ultima linha ate a primeira. de n a 0
    for j in range(u.shape[0]): #para calcular as somas possiveis
      if(j!=-i): #e possivel somar quando eu conheco o valor de x descoberto na linha anterior. acesso o vetor de solucoes atraves do indice j
        soma+=solucoes[j]*u[-i,j] #faco as somas possiveis
    solucoes[-i]=(d[-i]-soma)/u[-i,-i] #calculo a solucao
    soma=0.0 #zero o valor de soma para o proximo calculo na linha acima   
  print(solucoes)
  for k in range (u.shape[0]):
    print('x',k+1,' = ',solucoes[k],sep='') 
  return solucoes

def slu(matriz):
  l1,u1,b1=dlu(matriz)
  d1=matriz_d(l1,b1)
  return solucao(u1,d1)

def solucao_inversa(u,d):
  solucoes=np.zeros(u.shape[0],dtype=float) #vetor de solucoes
  solucoes[-1]=d[-1]/u[-1,-1] #a primeira solucao é conhecida
  soma=0.0
  for i in range(-(u.shape[0]-2),1): #vai da ultima linha ate a primeira. de n a 0
    for j in range(u.shape[0]): #para calcular as somas possiveis
      if(j!=-i): #e possivel somar quando eu conheco o valor de x descoberto na linha anterior. acesso o vetor de solucoes atraves do indice j
        soma+=solucoes[j]*u[-i,j] #faco as somas possiveis
    solucoes[-i]=(d[-i]-soma)/u[-i,-i] #calculo a solucao
    soma=0.0 #zero o valor de soma para o proximo calculo na linha acima    
  return solucoes

def pivotamento_lu_inversa(matriz_u,matriz_l):
  for i in range(matriz_u.shape[0]-1):
    maior=matriz_u[i,i] #maior = primeiro numero da coluna
    pivo=maior 
    equacao_pivo=matriz_u[i,:] #linha que representa a equacao pivo
    j=i+1 #para acessar as linhas a frente da pivo
    while(j<matriz_u.shape[0]): #enquanto nao chegar a ultima linha
      eliminador=matriz_u[j,i]/pivo #calculo o elemento que fara a eliminacao do termo
      matriz_u[j,:]=matriz_u[j,:]-(eliminador*equacao_pivo) #atualiza a linha que vai ter o elemento eliminado
      matriz_l[j,i]=eliminador #preenche a matriz l
      j=j+1 #acessa a proxima linha para fazer nova eliminacao
  return matriz_l,matriz_u

def dlu_inversa(matriz_sistema):
  u=matriz_sistema[:,:-1] #matriz dos coeficientes
  b=matriz_sistema[:,-1] #matriz dos resultados
  l=np.identity(u.shape[0],dtype=float) #identidade, matriz l
  l,u=pivotamento_lu_inversa(u,l) #chama função para encontrar l e u
  return l,u

def calcular_inversa(matriz):
  a=np.zeros(matriz.shape[0],dtype=float)
  matriz=np.vstack((matriz,a))
  a=np.zeros(matriz.shape[0],dtype=float)
  a=np.reshape(a,(-1,1))
  matriz=np.hstack((matriz,a))
  
  l,u=dlu_inversa(matriz)
  l1=l[:-1,:-1]
  u1=u[:-1,:]
  res=np.zeros((l1.shape[0],l1.shape[0]),dtype=float)
  b1=np.identity(l1.shape[0])
  for i in range(l1.shape[0]):
    d1=matriz_d(l1,b1[:,i])
    res[:,i]=solucao_inversa(u1,d1)
  return res

def calcular_erro(x1,x2):
  return np.abs((x1-x2)/x1)*100

def verificar_solucao(solutions,sistema,tol):
  res=0
  for i in range(sistema.shape[0]):
    soma=0.0
    for j in range(sistema.shape[1]-1):
      soma+=(round(solutions[j],10)*round(sistema[i,j],10))
    if(np.abs(soma-sistema[i,-1])<=tol):
      res+=1
    else:
      break
  if(res==sistema.shape[0]):
    print ('Solucões corretas!')
  else:
    print('Solucões incorretas! :/')


## Exercício 1
### Encontre a solução do seguinte sistema

$$ 25x_1+5x_2+x_3 = 106.8$$
$$ 64x_1+8x_2+x_3 = 177.2$$
$$ 144x_1+12x_2+x_3 = 279.2$$

utilizando o método de Gauss ingênuo

In [0]:
a1=np.array([[25.0,5.0,1.0,106.8],[64.0,8.0,1.0,177.2],[144.0,12.0,1.0,279.2]],dtype=float)
x_1=gauss_ingenuo(a1)
verificar_solucao(x_1,a1,.005)

[0.2905 19.6905 1.0857]
x1 = 0.2904761904761892
x2 = 19.690476190476197
x3 = 1.0857142857142739
Solucões corretas!


## Exercício 2
### Encontre a solução do seguinte sistema

$$      2x_2+3x_3 = 8$$
$$ 4x_1+6x_2+7x_3 = -3$$
$$ 2x_1+3x_2+6x_3 = 5$$

utilizando o método de Gauss ingênuo

In [0]:
a2=np.array([[0.0,2.0,3.0,8.0],[4.0,6.0,7.0,-3.0],[2.0,3.0,6.0,5.0]],dtype=float)
x_2=gauss_ingenuo(a2)
#impossivel resolver por gauss ingenuo, pois há uma divisao por 0

[nan nan nan]
x1 = nan
x2 = nan
x3 = nan


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in double_scalars
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in multiply
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in double_scalars
  # Remove the CWD from sys.path while we load stuff.


## Exercício 3
### Encontre a solução do seguinte sistema

$$      2x_2+3x_3 = 8$$
$$ 4x_1+6x_2+7x_3 = -3$$
$$ 2x_1+3x_2+6x_3 = 5$$

utilizando o método de Gauss com pivotação parcial

In [0]:
a3=np.array([[0.0,2.0,3.0,8.0],[4.0,6.0,7.0,-3.0],[2.0,3.0,6.0,5.0]],dtype=float)
x_3=gauss_pivotamento(a3)
verificar_solucao(x_3,a3,.001)

[-5.4500 0.1000 2.6000]
x1 = -5.45
x2 = 0.09999999999999964
x3 = 2.6
Solucões corretas!


## Exercício 4
Dado o sistema

$$\begin{bmatrix}
10x_1-x_2-2x_3=6\\
-x_1+11x_2-x_3+3x_4=25\\
2x_1-x_2+10x_3-x_4=-11\\
3x_2-x_3+8x_4 = 15
\end{bmatrix}$$

a. Verifique se a convergência pode ser garantida através do método de Gauss-Seidel.

b. Resolva o sistema utilizando Gauss-Seidel se  a convergência for garantida.

c. Resolva pelo método de Gauss com pivotação

comente sobre o resultado

In [0]:
a4=np.array([[10.0,-1.0,-2.0,0.0,6.0],[-1.0,11.0,-1.0,3.0,25.0],[2.0,-1.0,10.0,-1.0,-11.0],[0.0,3.0,-1.0,8.0,15.0]],dtype=float)
tol=.0001
#a e b
print('a/b:')
(verificar_dominancia(a4))
x_4b=gauss_seidel(a4,100,0.01,0,0.2)
verificar_solucao(x_4b,a4,tol)
#c
print('c:')
x_4c=gauss_pivotamento(a4)
verificar_solucao(x_4c,a4,tol)
#comentario: 
#O resultado está correto, foi conferido manualmente.
#A nao convergência se deve ao fato da diagonal nao ser dominante, por exemplo o num. 25 na segunda equação é muito maior que os outros

a/b:
O sistema não possui convergencia garantida
numero de iteracoes:  6
x1 = 0.6118396734627658
x2 = 1.965531337610947
x3 = -0.9235674553770012
x4 = 1.0224798164737696
Solucões corretas!
c:
[0.6118 1.9655 -0.9236 1.0225]
x1 = 0.6118396403147247
x2 = 1.96553016110903
x3 = -0.9235668789808916
x4 = 1.0224803297115024
Solucões corretas!


## Exercício 5
Resolva os sistemas utilizando um método direto e o método de Gauss-Seidel

a. 
    $$8.7x_1 + 3x_2 + 9.3x_3 + 11x_4 = 16.4$$
    $$24.5x_1 - 8.8x_2 + 11.5x_3 - 45.1x_4 = -49.7$$
    $$52.3x_1 - 84x_2 - 23.5x_3 + 11.4x_4 = -80.8$$
    $$21x_1 - 81x_2 - 13.2x_3 + 21.5x_4 = -106.3$$

In [0]:
a5=np.array([[8.7,3.0,9.3,11.0,16.4],[24.5,-8.8,11.5,-45.1,-49.7],[52.3,-84.0,-23.5,11.4,-80.8],[21.0,-81.0,13.2,21.5,-106.3]],dtype=float)
print('pivotamento:')
x_5=gauss_pivotamento(a5)
print('\ngauss-seidel:')
gauss_seidel(a5,100,0.01,0,0.2)
print('\ndecomposicao lu:')
slu(a5)
#as solucoes foram iguais, necessario apenas uma verificação
print('\n')
verificar_solucao(x_5,a5,.001)

pivotamento:
[0.6487 1.6541 -0.5497 0.9915]
x1 = 0.6486708990532252
x2 = 1.654111242947833
x3 = -0.549665874397542
x4 = 0.9914656437536887

gauss-seidel:
numero de iteracoes:  5
x1 = 0.6486708990532252
x2 = 1.654111242947833
x3 = -0.549665874397542
x4 = 0.9914656437536887

decomposicao lu:
[0.6487 1.6541 -0.5497 0.9915]
x1 = 0.6486708990532252
x2 = 1.654111242947833
x3 = -0.549665874397542
x4 = 0.9914656437536887


Solucões corretas!


b.

$$3x_1 + 7x_2 + 13x_3 = 76$$
$$12x_1 + 3x_2 - 5x_3 = 1$$
$$x_1 + 5x_2 + 3x_3 = 28$$

In [0]:
b5=np.array([[3,7,13,76],[12,3,-5,1],[1,5,3,28]],dtype=float)
print('pivotamento:')
x_5b=gauss_pivotamento(b5)
print('\ngauss-seidel:')
gauss_seidel(b5,100,0.01,0,0.2)
print('\ndecomposicao lu:')
slu(b5)

print('\n')
verificar_solucao(x_5b,b5,.001)

pivotamento:
[1.0000 3.0000 4.0000]
x1 = 0.9999999999999994
x2 = 3.0000000000000013
x3 = 3.9999999999999996

gauss-seidel:
numero de iteracoes:  4
x1 = 0.9999999999999994
x2 = 3.0000000000000013
x3 = 3.9999999999999996

decomposicao lu:
[1.0000 3.0000 4.0000]
x1 = 0.9999999999999994
x2 = 3.0000000000000013
x3 = 3.9999999999999996


Solucões corretas!


c.
    $$1x_2 + 3x_3 + 2x_4 + 4x_5 = 3$$
    $$8x_1 - 2x_2 + 9x_3 - 1x_4 + 2x_5 = -5$$
    $$5x_1 + x_2 + x_3 + 7x_4 + 2x_5 = 6$$
    $$-2x_1 + 4x_2 + 5x_3 + 1x_4 = -1$$
    $$7x_1 - 3x_2 + 2x_3 - 4x_4 + 1x_5 = -5$$


In [0]:
c5=np.array([[0,1,3,2,4,3],[8,-2,9,-1,2,-5],[5,1,1,7,2,6],[-2,4,5,1,0,-1],[7,-3,2,-4,1,-5]],dtype=float)
print('pivotamento:')
gauss_pivotamento(c5)
print('\ngauss-seidel:')
x_5c=gauss_seidel(c5,100,0.01,0,0.2)
print('\ndecomposicao lu:')
slu(c5)

print('\n')
verificar_solucao(x_5c,c5,.001)

pivotamento:
[-0.1900 -0.0172 -0.4369 0.8733 0.6453]
x1 = -0.18997995991983935
x2 = -0.01723446893787511
x3 = -0.43687374749499036
x4 = 0.8733466933867734
x5 = 0.6452905811623246

gauss-seidel:
numero de iteracoes:  6
x1 = -0.18997995991983935
x2 = -0.01723446893787511
x3 = -0.43687374749499036
x4 = 0.8733466933867734
x5 = 0.6452905811623246

decomposicao lu:
[-0.1900 -0.0172 -0.4369 0.8733 0.6453]
x1 = -0.18997995991983935
x2 = -0.01723446893787511
x3 = -0.43687374749499036
x4 = 0.8733466933867734
x5 = 0.6452905811623246


Solucões corretas!


## Exercício 6

Uma barra linear de metal de um metro de comprimento é mantida a 0 graus Celsius em um extremo e a 128 graus Celsius no outro. Desejamos determinar a temperatura da barra a cada 20cm . Denominando de T0 = 0 a temperatura de um extremo, de T5 = 128 a temperatura no outro extremo e de T1, T2, T3 e T4 a temperatura nos pontos interiores e sabendo que a temperatura em cada ponto interior é igual a média aritmética da temperatura de seus dois pontos vizinhos.

    Determine através de um método de resolução de sistemas lineares os valores de T1, T2, T3 e T4

In [0]:
a6=np.array([[2,-1,0,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0],[0,0,-1,2,128]],dtype=float)
aa6=a6.copy()
x_6=gauss_pivotamento(a6)
verificar_solucao(x_6,aa6,.5)
print('\n')
x_6b=gauss_seidel(a6,100,.01,0,.2)
verificar_solucao(x_6b,aa6,.5)

[25.6000 51.2000 76.8000 102.4000]
x1 = 25.599999999999998
x2 = 51.199999999999996
x3 = 76.8
x4 = 102.4
Solucões corretas!


numero de iteracoes:  5
x1 = 25.599999999999998
x2 = 51.199999999999996
x3 = 76.8
x4 = 102.4
Solucões corretas!


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:87: RuntimeWarning: invalid value encountered in double_scalars


## Exercício 7

Calcule a inversa das matrizes abaixo utilizando dois métodos de resolução de sistemas lineares

a.

$$A = \begin{bmatrix}
    8 & 5 & 1 \\
    3 & 7 & 4\\
    2 & 3 & 9 
\end{bmatrix}$$

In [0]:
a7=np.array([[8,5,1],[3,7,4],[2,3,9]],dtype=float)
z=calcular_inversa(a7)
print('inversa de A =')
print(z)
print('\nconferindo: np.dot(A,A^-1)\n')
print(np.dot(z,a7))

inversa de A =
[[0.1656 -0.1364 0.0422]
 [-0.0617 0.2273 -0.0942]
 [-0.0162 -0.0455 0.1331]]

conferindo: np.dot(A,A^-1)

[[1.0000 0.0000 0.0000]
 [0.0000 1.0000 -0.0000]
 [0.0000 0.0000 1.0000]]


b.
$$A = \begin{bmatrix}
        1 & 6 & 4 \\
        2 & -3 & 1\\
        5 & 5 & 8 
\end{bmatrix}$$

In [0]:
b7=np.array([[1,6,4],[2,-3,1],[5,5,8]],dtype=float)
z1=calcular_inversa(b7)
print('inversa de A =')
print(z1)
print('\nconferindo: np.dot(A,A^-1)\n')
print(np.dot(z1,b7))

inversa de A =
[[-5.8000 -5.6000 3.6000]
 [-2.2000 -2.4000 1.4000]
 [5.0000 5.0000 -3.0000]]

conferindo: np.dot(A,A^-1)

[[1.0000 0.0000 0.0000]
 [0.0000 1.0000 -0.0000]
 [0.0000 0.0000 1.0000]]


## Exercício 8

Calcular as tensões nos nós do circuito elétrico abaixo:

![](https://github.com/lacouth/metodos_numericos/blob/master/sistemas_lineares/circuito.png?raw=1)

## Modelagem matemática

Pela lei de *Kirchhoff*, a soma das correntes que passam em cada nó do circuito é nula. Pela lei de *Ohm* a corrente elétrica que flui do nó *j* para o nó *k* de um circuito é 

$$I_{jk} = \frac{V_j-V_k}{R_{jk}}$$

sendo $V_j$ e $V_k$ as tensões nos nós $j$  e $k$, respectivamente, e $R_{jk}$ a resistência no arco _jk_. A corrente $I$ é expressa em ampères e a resistência $R$, em ohms. As duas leis combinadas permitem o cálculo da tensão em cada nó do circuito.

No nó 1, pela lei de _Kirchoff_,

$$I_{A1} + I_{21} + I_{31} + I_{41} = 0 $$

Utilizando a lei de _Ohm_, 

$$ \frac{0-V_1}{1} + \frac{V_2-V_1}{1} + \frac{V_3-V_1}{2} + \frac{V_4-V_1}{2} = 0 $$

simplificando:

$$ -6V_1 + 2V_2 + V_3 + V_4 = 0$$


Determinando as equações dos nós 2, 3 e 4, constrói-se um sistema de equações lineares. O vetor solução fornece a tensão em cada nó do circuito elétrico.

Construa o resto do sistema e utilizando dois métodos de resolução numérica encontre as tensões em cada um dos nós.

In [0]:
a8=np.array([[3,0,1,0,127.0],[3,-4,1,0,0.0],[1,2,0,-3,0],[9,2,-11,6,0]])
print('pivotamento:')
gauss_pivotamento(a8)
print('\ndecomposiçao lu:')
x_8=slu(a8)
print('\ngauss ingenuo:')
gauss_ingenuo(a8)
print('\ngauss seidel:')
gauss_seidel(a8,100,.01,0,0.2)
print('\n')
verificar_solucao(x_8,a8,.8)

pivotamento:
[27.4205 31.7500 44.7386 30.3068]
x1 = 27.420454545454554
x2 = 31.750000000000004
x3 = 44.73863636363637
x4 = 30.30681818181818

decomposiçao lu:
[27.4205 31.7500 44.7386 30.3068]
x1 = 27.420454545454554
x2 = 31.750000000000004
x3 = 44.73863636363637
x4 = 30.30681818181818

gauss ingenuo:
[27.4205 31.7500 44.7386 30.3068]
x1 = 27.420454545454554
x2 = 31.750000000000004
x3 = 44.73863636363637
x4 = 30.30681818181818

gauss seidel:
numero de iteracoes:  5
x1 = 27.420454545454554
x2 = 31.750000000000004
x3 = 44.73863636363637
x4 = 30.30681818181818


Solucões corretas!
